services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=payment_db'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5433:5432'
